# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\QCRobot\Server\Part\UI\Stat_Cohort.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(844, 333)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Run_monitor = QtWidgets.QPushButton(Form)
        self.Run_monitor.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.Run_monitor.setFont(font)
        self.Run_monitor.setObjectName("Run_monitor")
        self.gridLayout.addWidget(self.Run_monitor, 5, 3, 1, 1)
        self.S_MQ = QtWidgets.QRadioButton(Form)
        self.S_MQ.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.S_MQ.setFont(font)
        self.S_MQ.setObjectName("S_MQ")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.S_MQ)
        self.gridLayout.addWidget(self.S_MQ, 1, 1, 1, 1)
        self.Output = QtWidgets.QPushButton(Form)
        self.Output.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.Output.setFont(font)
        self.Output.setObjectName("Output")
        self.gridLayout.addWidget(self.Output, 4, 0, 1, 1)
        self.Monitor_Dir = QtWidgets.QPushButton(Form)
        self.Monitor_Dir.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.Monitor_Dir.setFont(font)
        self.Monitor_Dir.setObjectName("Monitor_Dir")
        self.gridLayout.addWidget(self.Monitor_Dir, 2, 0, 1, 1)
        self.S_SP = QtWidgets.QRadioButton(Form)
        self.S_SP.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.S_SP.setFont(font)
        self.S_SP.setObjectName("S_SP")
        self.buttonGroup.addButton(self.S_SP)
        self.gridLayout.addWidget(self.S_SP, 1, 3, 1, 1)
        self.Monitor_File = QtWidgets.QPushButton(Form)
        self.Monitor_File.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.Monitor_File.setFont(font)
        self.Monitor_File.setObjectName("Monitor_File")
        self.gridLayout.addWidget(self.Monitor_File, 3, 0, 1, 1)
        self.S_MS = QtWidgets.QRadioButton(Form)
        self.S_MS.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.S_MS.setFont(font)
        self.S_MS.setObjectName("S_MS")
        self.buttonGroup.addButton(self.S_MS)
        self.gridLayout.addWidget(self.S_MS, 1, 2, 1, 1)
        self.Show_Dir = QtWidgets.QLineEdit(Form)
        self.Show_Dir.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.Show_Dir.setFont(font)
        self.Show_Dir.setObjectName("Show_Dir")
        self.gridLayout.addWidget(self.Show_Dir, 2, 1, 1, 3)
        self.Show_File = QtWidgets.QLineEdit(Form)
        self.Show_File.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.Show_File.setFont(font)
        self.Show_File.setObjectName("Show_File")
        self.gridLayout.addWidget(self.Show_File, 3, 1, 1, 3)
        self.Show_Output = QtWidgets.QLineEdit(Form)
        self.Show_Output.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.Show_Output.setFont(font)
        self.Show_Output.setObjectName("Show_Output")
        self.gridLayout.addWidget(self.Show_Output, 4, 1, 1, 3)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 4, QtCore.Qt.AlignHCenter)

        self.retranslateUi(Form)
        self.S_MQ.clicked['bool'].connect(self.Show_Dir.setVisible) # type: ignore
        self.S_MQ.clicked['bool'].connect(self.Show_File.setHidden) # type: ignore
        self.S_SP.clicked['bool'].connect(self.Show_Dir.setHidden) # type: ignore
        self.S_SP.clicked['bool'].connect(self.Show_File.setVisible) # type: ignore
        self.S_SP.clicked['bool'].connect(self.Monitor_Dir.setHidden) # type: ignore
        self.S_SP.clicked['bool'].connect(self.Monitor_File.setVisible) # type: ignore
        self.S_MQ.clicked['bool'].connect(self.Monitor_File.setHidden) # type: ignore
        self.S_MQ.clicked['bool'].connect(self.Monitor_Dir.setVisible) # type: ignore
        self.S_MS.clicked['bool'].connect(self.Show_Dir.setVisible) # type: ignore
        self.S_MS.clicked['bool'].connect(self.Show_File.setHidden) # type: ignore
        self.S_MS.clicked['bool'].connect(self.Monitor_Dir.setVisible) # type: ignore
        self.S_MS.clicked['bool'].connect(self.Monitor_File.setHidden) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Software"))
        self.Run_monitor.setText(_translate("Form", "Run"))
        self.S_MQ.setText(_translate("Form", "MaxQuant"))
        self.Output.setText(_translate("Form", "Output"))
        self.Monitor_Dir.setText(_translate("Form", "Monitor_Dir"))
        self.S_SP.setText(_translate("Form", "Spectronaut"))
        self.Monitor_File.setText(_translate("Form", "Monitor_File"))
        self.S_MS.setText(_translate("Form", "MSFragger"))
        self.label_5.setText(_translate("Form", "Cohort Data Statistics"))
